language: node_js
env:
  global:
    # gh-pagesへのdeploy向け
    - GH_USER_EMAIL="azuciao@gmail.com"
    - GH_USER_NAME="azu"
jobs:
  include:
    # Unit Tests
    - stage: test
      name: "Unit Tests on Node.js 12"
      node_js: '12'
      script: npm run travis
    # deploy
    - stage: deploy
      node_js: '12'
      if: branch = master AND type != pull_request
      before_script:
        - |

          $(npm bin)/set-up-ssh --key "$encrypted_55887fb399d9_key" \
                                --iv "$encrypted_55887fb399d9_iv" \
                                --path-encrypted-key ".travis/github_deploy_key.enc"
      script:
        - |
          npm run install:gitbook
          $(npm bin)/update-branch --commands "npm run build" \
                             --commit-message "Deploy GitBook build [skip ci]" \
                             --directory "_book" \
                             --distribution-branch "gh-pages" \
                             --source-branch "master"
